"""Repository contract consumed by use-case orchestration."""

from __future__ import annotations

from typing import Protocol

from trust_receipt.models.tasks import TaskSpec
from trust_receipt.models.verification import VerificationResult
from trust_receipt.services.ports import ReportDelivery
from trust_receipt.storage.models import AttemptRecord, StoredTask


class TaskRepository(Protocol):
    def add_task(self, task: TaskSpec) -> None: ...

    def get_task(self, task_id: str) -> StoredTask: ...

    def list_tasks(self) -> tuple[StoredTask, ...]: ...

    def request_attempt(self, task_id: str) -> int: ...

    def cancel_attempt_request(self, task_id: str) -> None: ...

    def save_delivery(self, delivery: ReportDelivery) -> None: ...

    def begin_verification(self, task_id: str, submission_id: str) -> None: ...

    def save_verification(self, result: VerificationResult) -> None: ...

    def get_attempt(self, task_id: str, attempt: int) -> AttemptRecord: ...

    def list_attempts(self, task_id: str) -> tuple[AttemptRecord, ...]: ...
