"""Closed M1 enumerations used across models and generated schemas."""

from enum import StrEnum


class EvidenceSource(StrEnum):
    RPC = "rpc"
    BLOCKSCOUT = "blockscout"
    SERVICE = "service"


class ExclusionRuleType(StrEnum):
    EXCLUDE_TREASURY_INTERNAL = "EXCLUDE_TREASURY_INTERNAL"


class VerificationOutcome(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    INCONCLUSIVE = "INCONCLUSIVE"


class FindingType(StrEnum):
    MISSING_TRANSFER = "MISSING_TRANSFER"
    EXTRA_TRANSFER = "EXTRA_TRANSFER"
    DUPLICATE_TRANSFER = "DUPLICATE_TRANSFER"
    EXCLUDED_INTERNAL_TRANSFER = "EXCLUDED_INTERNAL_TRANSFER"
    OUT_OF_RANGE = "OUT_OF_RANGE"
    WRONG_TOKEN = "WRONG_TOKEN"
    WRONG_DIRECTION = "WRONG_DIRECTION"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    DECIMAL_ERROR = "DECIMAL_ERROR"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class FindingSeverity(StrEnum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class FindingStatus(StrEnum):
    CONFIRMED = "confirmed"
    HYPOTHESIS = "hypothesis"


class ClaimType(StrEnum):
    CLAIMED_TOTAL = "CLAIMED_TOTAL"
    CLAIMED_COUNT = "CLAIMED_COUNT"
    TRANSFER_SET = "TRANSFER_SET"


class QueryType(StrEnum):
    FETCH_ERC20_TRANSFERS = "FETCH_ERC20_TRANSFERS"


class FilterType(StrEnum):
    TOKEN_ADDRESS = "TOKEN_ADDRESS"
    BLOCK_RANGE = "BLOCK_RANGE"
    TREASURY_DIRECTION = "TREASURY_DIRECTION"
    EXCLUDE_INTERNAL_TRANSFER = "EXCLUDE_INTERNAL_TRANSFER"
    RECIPIENT_SET = "RECIPIENT_SET"


class AggregationRuleType(StrEnum):
    SUM_BASE_UNITS = "SUM_BASE_UNITS"
    COUNT_TRANSFERS = "COUNT_TRANSFERS"


class CheckType(StrEnum):
    COMPARE_EVENT_SET = "COMPARE_EVENT_SET"
    COMPARE_TOTAL = "COMPARE_TOTAL"
    DETECT_DUPLICATES = "DETECT_DUPLICATES"
    VALIDATE_SCOPE = "VALIDATE_SCOPE"
    VALIDATE_TOKEN_DECIMALS = "VALIDATE_TOKEN_DECIMALS"


class PublicationChainStatus(StrEnum):
    NOT_SUBMITTED = "NOT_SUBMITTED"
    SUBMITTED = "SUBMITTED"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"


class CommitmentAnchorStatus(StrEnum):
    NOT_SUBMITTED = "NOT_SUBMITTED"
    SUBMITTED = "SUBMITTED"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"


class FundFlowNodeRole(StrEnum):
    TREASURY = "TREASURY"
    RECIPIENT = "RECIPIENT"
    EXTERNAL = "EXTERNAL"


class FundFlowVisualStatus(StrEnum):
    MATCHED = "MATCHED"
    MISSING_FROM_REPORT = "MISSING_FROM_REPORT"
    NOT_FOUND_ON_CHAIN = "NOT_FOUND_ON_CHAIN"
    INTERNAL_TRANSFER = "INTERNAL_TRANSFER"
    DUPLICATE = "DUPLICATE"
    INCONCLUSIVE = "INCONCLUSIVE"
    MISMATCH = "MISMATCH"
    INVALID_SCOPE = "INVALID_SCOPE"
